# Generated by Django 4.0.1 on 2022-01-17 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oil', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oil',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='oil',
            name='liter',
            field=models.IntegerField(default=0),
        ),
    ]
